
----- TABELA QUE REGISTRA ALTERAÇÕES DOS PRODUTOS
CREATE TABLE HIST_PROD (
ID_FUNC  INTEGER,
COD_PROD INTEGER,
DATA_PROD DATETIME,
QTD_RETIRADA INT,
QTD_ADICIONADA INT,
CONSTRAINT FK_COD_PROD FOREIGN KEY (COD_PROD) REFERENCES PRODUTOS(COD_PROD),
CONSTRAINT FK_ID_FUNC FOREIGN KEY (ID_FUNC) REFERENCES USUARIO(ID_FUNC)
)

//DROP TABLE HIST_PROD;


SELECT * FROM HIST_PROD;
