

CREATE TABLE dbo.USUARIO
	(
	ID_FUNC         IDENTITY NOT NULL AUTO_INCREMENT,
	NOME            VARCHAR (255) NOT NULL,
	SOBRENOME		VARCHAR (255) NOT NULL,
	CPF             VARCHAR (20) NOT NULL,
	DATA_NASCIMENTO DATE NULL,
	CARGO          	VARCHAR (255) NULL,
	CEP				VARCHAR(255) NOT NULL,
	ESTADO			VARCHAR(255) NOT NULL,
	RUA        		VARCHAR (255) NULL,
	NUM_C	   		VARCHAR(255),
	TELEFONE		VARCHAR(255) NOT NULL,
	EMAIL			VARCHAR(255) NOT NULL,
	SENHA			VARCHAR(255) NOT NULL,
	NIVEL			VARCHAR(5),
	DT_CADASTRO		DATETIME,
	PRIMARY KEY (ID_FUNC)
	)
GO

DROP TABLE USUARIO;

SELECT * FROM USUARIO;


INSERT INTO USUARIO (ID_FUNC, NOME, SOBRENOME, CPF, DATA_NASCIMENTO, CARGO, CEP, ESTADO, RUA, NUM_C, TELEFONE, EMAIL, SENHA, NIVEL, DT_CADASTRO)
VALUES 				(1, 'WANGLER', 'JUNER', '12345678912', '22/02/1999', 'AUXILIAR DE LIMPEZA', '14876165', 'SP', 'RUA DO CENTRO', '666', '16993129292','wangler@juner.com','123','1', GETDATE())

